backend:
  name: github
  repo: kaifkhan2981/hooria-builders
  branch: main
  base_url: https://hooria-builders-main-xn6h-9zslauiwf.vercel.app # Updated per user request
  auth_endpoint: api/auth

media_folder: "hooria-builders-main/assets/images"
public_folder: "assets/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "hooria-builders-main/projects"
    extension: "md"
    format: "yaml-frontmatter"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
